
--CREATE SEQUENCES FOR PRIMARY KEYS(PK)
CREATE SEQUENCE seq_customer START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE seq_product START WITH 2001 INCREMENT BY 1;
CREATE SEQUENCE seq_user START WITH 3001 INCREMENT BY 1;
CREATE SEQUENCE seq_order START WITH 4001 INCREMENT BY 1;
CREATE SEQUENCE seq_error START WITH 5001 INCREMENT BY 1;
CREATE SEQUENCE seq_session START WITH 6001 INCREMENT BY 1;
CREATE SEQUENCE seq_history START WITH 7001 INCREMENT BY 1;
CREATE SEQUENCE seq_feedback START WITH 8001 INCREMENT BY 1;
CREATE SEQUENCE seq_inventory_audit START WITH 9001 INCREMENT BY 1;
CREATE SEQUENCE seq_payment START WITH 10001 INCREMENT BY 1;
CREATE SEQUENCE seq_config START WITH 11001 INCREMENT BY 1;
CREATE SEQUENCE seq_audit_trail START WITH 12001 INCREMENT BY 1;
CREATE SEQUENCE seq_holiday START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_audit_log START WITH 1 INCREMENT BY 1;